version: '3.7'

services:
  vc_slack_bot:
    container_name: vc_slack_bot
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - 8080:8080
    stdin_open: true
    env_file:
      - .env
